CREATE DATABASE IF NOT EXISTS gestao_projetos;
USE gestao_projetos;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  login VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(60) NOT NULL,
  perfil ENUM('ADMIN','GERENTE','COLABORADOR') NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS projetos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao TEXT,
  data_inicio DATE,
  data_fim DATE,
  status ENUM('PLANEJAMENTO','ANDAMENTO','CONCLUIDO') NOT NULL,
  gerente_id INT,
  CONSTRAINT fk_proj_user FOREIGN KEY (gerente_id) REFERENCES usuarios(id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;
